package com.slavikjunior.models

import com.slavikjunior.deorm.annotations.Column
import com.slavikjunior.deorm.annotations.Id
import com.slavikjunior.deorm.annotations.Table
import com.slavikjunior.deorm.orm.Entity
import java.math.BigDecimal
import java.sql.Timestamp
import java.sql.Types

@Table(name = "users")
data class User
@JvmOverloads
constructor(
    @Id(autogenerated = true)
    @Column(name = "id", type = Types.INTEGER, nullable = false)
    val id: Int,

    @Column(name = "login", type = Types.VARCHAR, nullable = false)
    val login: String,

    @Column(name = "password", type = Types.VARCHAR, nullable = false)
    val password: String,

    @Column(name = "email", type = Types.VARCHAR, nullable = false)
    val email: String,

    @Column(name = "created_at", type = Types.TIMESTAMP, nullable = true)
    val createdAt: Timestamp = Timestamp(System.currentTimeMillis())
) : Entity

@Table(name = "income_transactions")
data class IncomeTransaction
@JvmOverloads
constructor(
    @Id(autogenerated = true)
    @Column(name = "id", type = Types.INTEGER, nullable = false)
    val id: Int = 0,

    @Column(name = "user_id", type = Types.INTEGER, nullable = false)
    val userId: Int,

    @Column(name = "amount", type = Types.DECIMAL, nullable = false)
    val amount: BigDecimal,

    @Column(name = "category", type = Types.VARCHAR, nullable = false)
    val category: String,

    @Column(name = "description", type = Types.VARCHAR, nullable = true)
    val description: String? = null,

    @Column(name = "created_at", type = Types.TIMESTAMP, nullable = true)
    val createdAt: Timestamp = Timestamp(System.currentTimeMillis())
) : Entity

@Table(name = "expense_transactions")
data class ExpenseTransaction
@JvmOverloads
constructor(
    @Id(autogenerated = true)
    @Column(name = "id", type = Types.INTEGER, nullable = false)
    val id: Int = 0,

    @Column(name = "user_id", type = Types.INTEGER, nullable = false)
    val userId: Int,

    @Column(name = "amount", type = Types.DECIMAL, nullable = false)
    val amount: BigDecimal,

    @Column(name = "category", type = Types.VARCHAR, nullable = false)
    val category: String,

    @Column(name = "description", type = Types.VARCHAR, nullable = true)
    val description: String? = null,

    @Column(name = "created_at", type = Types.TIMESTAMP, nullable = true)
    val createdAt: Timestamp = Timestamp(System.currentTimeMillis())
) : Entity

@Table(name = "income_categories")
data class IncomeCategory
@JvmOverloads
constructor(
    @Id(autogenerated = true)
    @Column(name = "id", type = Types.INTEGER, nullable = false)
    val id: Int,

    @Column(name = "name", type = Types.VARCHAR, nullable = false)
    val name: String,

    @Column(name = "description", type = Types.VARCHAR, nullable = true)
    val description: String? = null
) : Entity

@Table(name = "expense_categories")
data class ExpenseCategory
@JvmOverloads
constructor(
    @Id(autogenerated = true)
    @Column(name = "id", type = Types.INTEGER, nullable = false)
    val id: Int,

    @Column(name = "name", type = Types.VARCHAR, nullable = false)
    val name: String,

    @Column(name = "description", type = Types.VARCHAR, nullable = true)
    val description: String? = null
) : Entity

@Table(name = "tags")
data class Tag
@JvmOverloads
constructor(
    @Id(autogenerated = true)
    @Column(name = "id", type = Types.INTEGER, nullable = false)
    val id: Int,

    @Column(name = "name", type = Types.VARCHAR, nullable = false)
    val name: String,

    @Column(name = "user_id", type = Types.INTEGER, nullable = false)
    val userId: Int,

    @Column(name = "color", type = Types.VARCHAR, nullable = true)
    val color: String? = "#3498db",

    @Column(name = "created_at", type = Types.TIMESTAMP, nullable = true)
    val createdAt: Timestamp = Timestamp(System.currentTimeMillis())
) : Entity

@Table(name = "transaction_tags")
data class TransactionTag(
    @Id(autogenerated = true)
    @Column(name = "id", type = Types.INTEGER, nullable = false)
    val id: Int,

    @Column(name = "transaction_id", type = Types.INTEGER, nullable = false)
    val transactionId: Int,

    @Column(name = "tag_id", type = Types.INTEGER, nullable = false)
    val tagId: Int,

    @Column(name = "transaction_type", type = Types.VARCHAR, nullable = false)
    val transactionType: String
) : Entity