package com.slavikjunior.models

import com.slavikjunior.deorm.annotations.Column
import com.slavikjunior.deorm.annotations.Id
import com.slavikjunior.deorm.annotations.Table
import com.slavikjunior.deorm.orm.Entity
import java.math.BigDecimal
import java.sql.Timestamp
import java.sql.Types

@Table(name = "users")
data class User
@JvmOverloads
constructor(
    @Id(autogenerated = true)
    @Column(name = "id", type = Types.INTEGER, nullable = false)
    val id: Int,

    @Column(name = "login", type = Types.VARCHAR, nullable = false)
    val login: String,

    @Column(name = "password", type = Types.VARCHAR, nullable = false)
    val password: String,

    @Column(name = "email", type = Types.VARCHAR, nullable = false)
    val email: String,

    @Column(name = "created_at", type = Types.TIMESTAMP, nullable = true)
    val createdAt: Timestamp = Timestamp(System.currentTimeMillis())
) : Entity

@Table(name = "transactions")
data class Transaction
@JvmOverloads
constructor(
    @Id(autogenerated = true)
    @Column(name = "id", type = java.sql.Types.INTEGER, nullable = false)
    val id: Int = 0,

    @Column(name = "user_id", type = java.sql.Types.INTEGER, nullable = false)
    val userId: Int,

    @Column(name = "amount", type = java.sql.Types.DECIMAL, nullable = false)
    val amount: BigDecimal,

    @Column(name = "category", type = java.sql.Types.VARCHAR, nullable = false)
    val category: String,

    @Column(name = "description", type = java.sql.Types.VARCHAR, nullable = true)
    val description: String? = null,

    @Column(name = "created_at", type = java.sql.Types.TIMESTAMP, nullable = true)
    val createdAt: Timestamp = Timestamp(System.currentTimeMillis()),

    @Column(name = "type", type = java.sql.Types.VARCHAR, nullable = false)
    val type: String
) : Entity

@Table(name = "categories")
data class Category(
    @Id(autogenerated = true)
    @Column(name = "id", type = java.sql.Types.INTEGER, nullable = false)
    val id: Int,

    @Column(name = "name", type = java.sql.Types.VARCHAR, nullable = false)
    val name: String,

    @Column(name = "description", type = java.sql.Types.VARCHAR, nullable = true)
    val description: String? = null
) : Entity