package com.slavikjunior.models

import com.slavikjunior.liba.annotations.*
import com.slavikjunior.liba.orm.Entity
import java.sql.Types

@Table(name = "persons")
data class Person(
    @Id(autogenerated = true)
    @Column(name = "id", type = Types.INTEGER, nullable = false)
    var id: Int,
    @Column(name = "firstname", type = Types.VARCHAR, nullable = true)
    var firstName: String? = null,
    @Column(name = "lastname", type = Types.VARCHAR, nullable = true)
    var lastName: String? = null,
    @Column(name = "email", type = Types.VARCHAR, nullable = true)
    var email: String? = null,
    @Column(name = "gender", type = Types.VARCHAR, nullable = true)
    var gender: String? = null,
    @Column(name = "ipaddress", type = Types.VARCHAR, nullable = true)
    var ipAddress: String? = null,
    @Column(name = "country", type = Types.VARCHAR, nullable = true)
    var country: String? = null
): Entity